name: Pre-Release

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  release:
    name: Pre-Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 18

      - name: Install dependencies
        run: pnpm install

      - name: Check code
        run: pnpm check

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm changeset pre enter beta && pnpm release
          commit: "feat(pre-release): version packages"
          title: "feat(pre-release): version packages"
          branch: prerelease
          publish: pnpm pub:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}